services:
  classfinder:
    build:
      context: .
    ports:
      - 7842:7842
    volumes:
      - ./data:/data
    restart: always
    hostname: classfinder
    stop_signal: SIGINT
    stop_grace_period: 3s